dataset_root: "/home/ubuntu/dataset/lerobot_dataset/crane_plus_pekori"
repo_id: "crane_plus_pekori"
output_directory: "/home/ubuntu/checkpoints/train/crane_plus_pekori_act"
config_path: "configs/crane_features.py"

device: "cpu"
training_steps: 500
log_freq: 1
num_workers: 2
batch_size: 2
chunk_size: 16
n_action_steps: 1
learning_rate: 0.0001
delta_timestamps:
  observation.environment_state: [0.0]
  observation.state: [0.0]
  action: [-0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4]