#dataset_root: "/root/pai_ws/src/dataset/lerobot_dataset/crane_plus_pekori"
dataset_root: "/home/ubuntu/dataset/rosbags/lerobot_pick_and_place"
repo_id: "crane_plus_pekori"
#output_directory: "/root/pai_ws/src/checkpoints/train/crane_plus_pekori_act"
output_directory: "/root/pai_ws/src/checkpoints/train/pick_and_place_act_13:25"
config_path: "configs/crane_features.py"

device: "cuda"
training_steps: 1500
log_freq: 1
num_workers: 2
batch_size: 8
chunk_size: 32
n_action_steps: 1
learning_rate: 0.00001
delta_timestamps:
  observation.environment_state: [0.0]
  observation.state: [0.0]
  action: [
    -0.1, 0.0, 0.1, 0.2,
    0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3,
    1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4,
    2.5, 2.6, 2.7, 2.8, 2.9, 3.0
  ]
